In [1]:
%matplotlib inline

import pandas as pd
import numpy as np
from scipy.stats import rv_continuous, norm, truncnorm, arcsine, chi2, gamma, triang, entropy
import matplotlib.pyplot as plt
from itertools import combinations_with_replacement
from time import time

In [99]:
gift_types = ['horse', 'ball', 'bike', 'train', 'coal', 'book', 'doll', 'block', 'gloves']
gift_numbers = [1000, 1100, 500, 1000, 166, 1200, 1000, 1000, 200]

In [53]:
convolutions = pd.read_csv('convolutions2_1001_20.csv')

In [63]:
a = convolutions.to_dict(orient='split')
data_list[0:10]

[["['gloves']", 1.375],
 ["['book']", 1.99989583587],
 ["['ball']", 2.00000000003],
 ["['gloves', 'gloves']", 2.75],
 ["['ball', 'gloves']", 3.37500000004],
 ["['book', 'gloves']", 3.39215494856],
 ["['ball', 'ball']", 4.00000000008],
 ["['ball', 'book']", 4.0250000002499995],
 ["['book', 'book']", 4.0499973708],
 ["['gloves', 'gloves', 'gloves']", 4.125]]

In [83]:
def treat_combination_str(comb_str, gift_types):
    clean_str = "".join([char for char in comb_str if char not in '[]\' '])
    items_list = clean_str.split(',')
    gift_numbers = [items_list.count(gift_type) for gift_type in gift_types]
    return gift_numbers

In [101]:
data_list = a['data']
new_dict = {}
for index, row in enumerate(data_list):
    gift_numbers = treat_combination_str(row[0], gift_types)
    row_score = row[1]
    new_dict[index] = gift_numbers + [row_score]

In [110]:
b = pd.DataFrame(new_dict).transpose()

In [114]:
b.columns = gift_types+['score']

In [120]:
b[gift_types] = b[gift_types].astype(int)

In [122]:
b = b.sort_values('score')

In [137]:
b.to_csv('convolutions_1001_20_ready.csv', index=False)

In [138]:
b

,horse,ball,bike,train,coal,book,doll,block,gloves,score,n_items
0,0,0,0,0,0,0,0,0,1,1.375000,1
1,0,0,0,0,0,1,0,0,0,1.999896,1
2,0,1,0,0,0,0,0,0,0,2.000000,1
3,0,0,0,0,0,0,0,0,2,2.750000,2
4,0,1,0,0,0,0,0,0,1,3.375000,2
5,0,0,0,0,0,1,0,0,1,3.392155,2
6,0,2,0,0,0,0,0,0,0,4.000000,2
7,0,1,0,0,0,1,0,0,0,4.025000,2
8,0,0,0,0,0,2,0,0,0,4.049997,2
9,0,0,0,0,0,0,0,0,3,4.125000,3
10,0,1,0,0,0,0,0,0,2,4.750000,3
11,0,0,0,0,0,1,0,0,2,4.784414,3
12,0,0,0,0,0,0,1,0,0,5.000000,1
13,1,0,0,0,0,0,0,0,0,5.035274,1
14,0,2,0,0,0,0,0,0,1,5.375000,3
15,0,1,0,0,0,1,0,0,1,5.417259,3
16,0,0,0,0,0,2,0,0,1,5.459732,3
17,0,0,0,0,0,0,0,0,4,5.500000,4
18,0,3,0,0,0,0,0,0,0,6.000000,3
19,0,2,0,0,0,1,0,0,0,6.050104,3
20,0,1,0,0,0,2,0,0,0,6.100521,3
21,0,1,0,0,0,0,0,0,3,6.125000,4
22,0,0,0,0,0,3,0,0,0,6.151250,3
23,0,0,0,0,0,1,0,0,3,6.176673,4
24,0,0,0,0,0,0,1,0,1,6.375000,2
25,1,0,0,0,0,0,0,0,1,6.410574,2
26,0,2,0,0,0,0,0,0,2,6.750000,4
27,0,1,0,0,0,1,0,0,2,6.809518,4
28,0,0,0,0,0,2,0,0,2,6.869467,4
29,0,0,0,0,0,0,0,0,5,6.875000,5
...,...,...,...,...,...,...,...,...,...,...,...
28319,1,16,0,0,0,3,0,0,0,41.446308,20
28320,0,15,0,0,0,0,0,1,0,41.446612,16
28321,2,15,0,0,0,1,0,0,0,41.479282,18
28322,0,17,0,0,0,2,1,0,0,41.483717,20
28323,0,1,0,0,0,18,0,0,0,41.488203,19
28324,0,1,0,0,0,18,0,0,1,41.502130,20
28325,1,16,0,0,0,0,1,0,1,41.512557,19
28326,2,15,0,0,0,0,0,0,2,41.513118,19
28327,0,3,0,0,0,17,0,0,0,41.527848,20
28328,1,17,0,0,0,0,0,0,2,41.557898,20
28329,0,0,0,0,0,19,0,0,1,41.650942,20
28330,0,2,0,0,0,18,0,0,0,41.652521,20
28331,0,0,0,0,0,19,0,0,0,41.664442,19
28332,2,16,0,0,0,1,0,0,0,41.709219,19
28333,3,14,0,0,0,0,0,0,0,41.724105,17
28334,0,1,0,0,0,19,0,0,0,41.786943,20
28335,0,18,0,0,0,0,1,0,1,41.799299,20
28336,1,17,0,0,0,1,0,0,1,41.825964,20
28337,2,16,0,0,0,0,0,0,0,41.854317,18
28338,0,16,0,0,0,0,0,1,0,41.857117,17
28339,1,17,0,0,0,2,0,0,0,41.890287,20
28340,0,0,0,0,0,20,0,0,0,41.930852,20
28341,0,18,0,0,0,1,1,0,0,41.938562,20
28342,1,17,0,0,0,0,1,0,0,42.015998,19
28343,2,16,0,0,0,0,0,0,1,42.105918,19
28344,1,18,0,0,0,0,0,0,1,42.257941,20
28345,1,18,0,0,0,1,0,0,0,42.400770,20
28346,0,19,0,0,0,0,1,0,0,42.438346,20
28347,2,17,0,0,0,0,0,0,0,42.766467,19
28348,1,19,0,0,0,0,0,0,0,42.959803,20

In [135]:
b['n_items'] = b.apply(lambda row: int(sum(row[gift_types])), axis=1)

In [136]:
b

,horse,ball,bike,train,coal,book,doll,block,gloves,score,n_items
0,0,0,0,0,0,0,0,0,1,1.375000,1
1,0,0,0,0,0,1,0,0,0,1.999896,1
2,0,1,0,0,0,0,0,0,0,2.000000,1
3,0,0,0,0,0,0,0,0,2,2.750000,2
4,0,1,0,0,0,0,0,0,1,3.375000,2
5,0,0,0,0,0,1,0,0,1,3.392155,2
6,0,2,0,0,0,0,0,0,0,4.000000,2
7,0,1,0,0,0,1,0,0,0,4.025000,2
8,0,0,0,0,0,2,0,0,0,4.049997,2
9,0,0,0,0,0,0,0,0,3,4.125000,3
10,0,1,0,0,0,0,0,0,2,4.750000,3
11,0,0,0,0,0,1,0,0,2,4.784414,3
12,0,0,0,0,0,0,1,0,0,5.000000,1
13,1,0,0,0,0,0,0,0,0,5.035274,1
14,0,2,0,0,0,0,0,0,1,5.375000,3
15,0,1,0,0,0,1,0,0,1,5.417259,3
16,0,0,0,0,0,2,0,0,1,5.459732,3
17,0,0,0,0,0,0,0,0,4,5.500000,4
18,0,3,0,0,0,0,0,0,0,6.000000,3
19,0,2,0,0,0,1,0,0,0,6.050104,3
20,0,1,0,0,0,2,0,0,0,6.100521,3
21,0,1,0,0,0,0,0,0,3,6.125000,4
22,0,0,0,0,0,3,0,0,0,6.151250,3
23,0,0,0,0,0,1,0,0,3,6.176673,4
24,0,0,0,0,0,0,1,0,1,6.375000,2
25,1,0,0,0,0,0,0,0,1,6.410574,2
26,0,2,0,0,0,0,0,0,2,6.750000,4
27,0,1,0,0,0,1,0,0,2,6.809518,4
28,0,0,0,0,0,2,0,0,2,6.869467,4
29,0,0,0,0,0,0,0,0,5,6.875000,5
...,...,...,...,...,...,...,...,...,...,...,...
28319,1,16,0,0,0,3,0,0,0,41.446308,20
28320,0,15,0,0,0,0,0,1,0,41.446612,16
28321,2,15,0,0,0,1,0,0,0,41.479282,18
28322,0,17,0,0,0,2,1,0,0,41.483717,20
28323,0,1,0,0,0,18,0,0,0,41.488203,19
28324,0,1,0,0,0,18,0,0,1,41.502130,20
28325,1,16,0,0,0,0,1,0,1,41.512557,19
28326,2,15,0,0,0,0,0,0,2,41.513118,19
28327,0,3,0,0,0,17,0,0,0,41.527848,20
28328,1,17,0,0,0,0,0,0,2,41.557898,20
28329,0,0,0,0,0,19,0,0,1,41.650942,20
28330,0,2,0,0,0,18,0,0,0,41.652521,20
28331,0,0,0,0,0,19,0,0,0,41.664442,19
28332,2,16,0,0,0,1,0,0,0,41.709219,19
28333,3,14,0,0,0,0,0,0,0,41.724105,17
28334,0,1,0,0,0,19,0,0,0,41.786943,20
28335,0,18,0,0,0,0,1,0,1,41.799299,20
28336,1,17,0,0,0,1,0,0,1,41.825964,20
28337,2,16,0,0,0,0,0,0,0,41.854317,18
28338,0,16,0,0,0,0,0,1,0,41.857117,17
28339,1,17,0,0,0,2,0,0,0,41.890287,20
28340,0,0,0,0,0,20,0,0,0,41.930852,20
28341,0,18,0,0,0,1,1,0,0,41.938562,20
28342,1,17,0,0,0,0,1,0,0,42.015998,19
28343,2,16,0,0,0,0,0,0,1,42.105918,19
28344,1,18,0,0,0,0,0,0,1,42.257941,20
28345,1,18,0,0,0,1,0,0,0,42.400770,20
28346,0,19,0,0,0,0,1,0,0,42.438346,20
28347,2,17,0,0,0,0,0,0,0,42.766467,19
28348,1,19,0,0,0,0,0,0,0,42.959803,20